services:
  maizzle: &maizzle
    build:
      context: .
      dockerfile: ./mise/containers/maizzle/Dockerfile
    image: handsomefencer/club/maizzle 

  dev:
    <<: *maizzle
    command: npm run dev
    ports:
      - "3002:3002"
      - "3003:3003"
    restart: on-failure
    volumes:
      - .:/artifact

volumes:
  node_modules:
  maizzle:
