# syntax=docker/dockerfile:1

FROM handsomefencer/club:development AS builder

RUN apk add --update --no-cache \
  graphviz \
  font-noto \ 
  fontconfig \ 
  && apk cache -v sync

FROM builder AS erd

COPY --from=builder \
  /usr/local/bundle /usr/local/bundle

COPY --from=builder \
  /app /app

COPY . .