# syntax=docker/dockerfile:1

FROM handsomefencer/club:development AS builder

RUN apk add --update --no-cache \
  chromium-chromedriver \ 
  && apk cache -v sync

FROM builder AS test

COPY --from=builder \
  /usr/local/bundle /usr/local/bundle

COPY --from=builder \
  /app /app

COPY . .